CREATE DATABASE website;

USE website;

CREATE TABLE `account` (
  `accountId` int(11) NOT NULL auto_increment,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `createdOn` timestamp NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY  (`accountId`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci auto_increment = 1;

CREATE TABLE `product` (
  `productId` int(11) NOT NULL auto_increment,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `descriptionDutch` text NOT NULL,
  `descriptionFrench` text NOT NULL,
  `descriptionEnglish` text NOT NULL,
  `price` float NOT NULL,
  PRIMARY KEY (`productId`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci auto_increment = 1;

CREATE TABLE `basketItem` (
  `AID` int(11) NOT NULL,
  `PID` int(11) NOT NULL,
  `quantity` int(11) NOT NULL,
  PRIMARY KEY (`AID`, `PID`),
  FOREIGN KEY (`AID`) REFERENCES `account` (`accountId`),
  FOREIGN KEY (`PID`) REFERENCES `product` (`productId`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE TABLE `message` (
  `messageId` int(11) NOT NULL auto_increment,
  `AID` int(11) NOT NULL,
  `message` text NOT NULL,
  `createdOn` datetime NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY  (`messageId`),
  FOREIGN KEY (`AID`) REFERENCES `account` (`accountId`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci auto_increment = 1;

INSERT INTO `product`(`name`, `image`, `descriptionDutch`, `descriptionFrench`, `descriptionEnglish`, `price`) VALUES ('Hwayo 53 Soju','../../includes/south-korea.jpg',"Hwayo 53 is een eersteklas Koreaanse soju die bekend staat om zijn uitzonderlijke kwaliteit en zachte smaak. Gedistilleerd uit 100% Koreaanse rijst, heeft het een alcoholpercentage van 53%, wat hoger is dan traditionele soju, en biedt het een verfijnd en schoon smaakprofiel met subtiele zoetheid en een vleugje bloemige noten. Zowel puur als in cocktails.","Hwayo 53 est un soju coréen haut de gamme connu pour sa qualité exceptionnelle et son goût doux. Distillé à partir de riz 100 % coréen, il affiche une teneur en alcool de 53 %, ce qui est plus élevé que le soju traditionnel. Il offre un profil de goût raffiné et pur, avec une douceur subtile et un soupçon de notes florales. Il se déguste aussi bien pur que dans des cocktails.","Hwayo 53 is a premium Korean soju known for its exceptional quality and smooth taste. Distilled from 100% Korean rice, it boasts a 53% alcohol content, which is higher than traditional soju, offering a refined and clean flavor profile with subtle sweetness and a hint of floral notes. Enjoyed both straight and in cocktails.",'83.5');

INSERT INTO `product`(`name`, `image`, `descriptionDutch`, `descriptionFrench`, `descriptionEnglish`, `price`) VALUES ('Jamazakura blended whiskey','../../includes/japan.jpg',"Jamazakura Blended Whiskey is een harmonieuze samensmelting van Japanse en Schotse whiskytradities. Hij is met precisie gemaakt en combineert malt- en graanwhisky's, wat resulteert in een evenwichtig en zacht profiel. Het delicate aroma van kersenbloesem en hints van turf creëren een unieke, plezierige drinkervaring, die de essentie van beide culturen bevat.","Le Blended Whiskey Jamazakura est une fusion harmonieuse des traditions japonaise et écossaise en matière de whisky. Élaboré avec précision, il associe des whiskies de malt et de grain, ce qui lui confère un profil équilibré et doux. Son arôme délicat de fleur de cerisier et ses notes de tourbe créent une expérience de consommation unique et agréable, capturant l'essence des deux cultures.","Jamazakura Blended Whiskey is a harmonious fusion of Japanese and Scottish whisky traditions. Crafted with precision, it combines malt and grain whiskies, resulting in a balanced and smooth profile. Its delicate cherry blossom aroma and hints of peat create a unique, enjoyable drinking experience, capturing the essence of both cultures.",'62');

INSERT INTO `product`(`name`, `image`, `descriptionDutch`, `descriptionFrench`, `descriptionEnglish`, `price`) VALUES ('Ming River Sichuan Baijiu','../../includes/china.jpg',"Ming River Sichuan Baijiu is een eersteklas Chinese gedistilleerde drank die bekend staat om zijn rijke erfgoed en gedurfde smaak. Hij wordt gemaakt in de provincie Sichuan van sorghum, tarwe, gerst en water uit de regio. Deze Baijiu heeft complexe, kruidige en fruitige noten, waardoor het een gekoesterde culturele traditie en een unieke smaakervaring is.","Le Ming River Sichuan Baijiu est un spiritueux chinois de première qualité, réputé pour son riche héritage et son goût prononcé. Fabriqué dans la province du Sichuan, il est élaboré à partir de sorgho, de blé, d'orge et d'eau de la région. Ce Baijiu présente des notes complexes, épicées et fruitées, ce qui en fait une tradition culturelle précieuse et une expérience gustative unique.","Ming River Sichuan Baijiu is a premium Chinese spirit renowned for its rich heritage and bold flavor. Crafted in Sichuan province, it's made from sorghum, wheat, barley, and water from the region. This Baijiu boasts complex, spicy, and fruity notes, making it a cherished cultural tradition and a unique taste experience.",'40');

INSERT INTO `product`(`name`, `image`, `descriptionDutch`, `descriptionFrench`, `descriptionEnglish`, `price`) VALUES ('Sang Som Special rum','../../includes/thailand.jpg',"Sang Som Special Rum is een gerenommeerde Thaise spirit die bekend staat om zijn rijke en zachte smaakprofiel. Gedistilleerd uit suikerriet, heeft het een harmonieuze mix van karamel, vanille en tropisch fruit, met een subtiele, verwarmende finish. Deze bekroonde rum is een geliefde keuze voor zowel cocktails als nippen.","Le rhum spécial Sang Som est un spiritueux thaïlandais réputé pour sa saveur riche et douce. Distillé à partir de canne à sucre, il présente un mélange harmonieux de notes de caramel, de vanille et de fruits tropicaux, avec une finale subtile et chaleureuse. Ce rhum primé est un choix apprécié pour les cocktails comme pour la dégustation.","Sang Som Special Rum is a renowned Thai spirit known for its rich and smooth flavor profile. Distilled from sugarcane, it features a harmonious blend of caramel, vanilla, and tropical fruit notes, with a subtle, warming finish. This award-winning rum is a beloved choice for cocktails and sipping alike.",'30');

INSERT INTO `product`(`name`, `image`, `descriptionDutch`, `descriptionFrench`, `descriptionEnglish`, `price`) VALUES ('KingFisher beer','../../includes/India.jpeg',"Kingfisher Beer is een gerenommeerd Indiaas pilsbier dat bekend staat om zijn verfrissende smaak en knapperige, gouden uiterlijk. Gebrouwen door United Breweries Group, biedt het een evenwichtige mix van mout en hop, die zorgt voor een zuivere, bevredigende ervaring met een vleugje citrustonen. Het is een populaire keuze voor bierliefhebbers over de hele wereld.","La bière Kingfisher est une bière blonde indienne réputée pour son goût rafraîchissant et son aspect vif et doré. Brassée par United Breweries Group, elle offre un mélange équilibré de malt et de houblon, offrant une expérience propre et satisfaisante avec une touche de notes d'agrumes. C'est un choix populaire pour les amateurs de bière du monde entier.","Kingfisher Beer is a renowned Indian lager known for its refreshing taste and crisp, golden appearance. Brewed by United Breweries Group, it offers a balanced blend of malt and hops, delivering a clean, satisfying experience with a touch of citrus notes. It's a popular choice for beer enthusiasts worldwide.",'48');

INSERT INTO `product`(`name`, `image`, `descriptionDutch`, `descriptionFrench`, `descriptionEnglish`, `price`) VALUES ('Bia Hoi Saigon Beer','../../includes/vietnam.png',"Bia Hoi Saigon is een populair Vietnamees bier dat bekend staat om zijn verfrissende en lichte karakter. Het wordt dagelijks gebrouwen en is een unieke ervaring op straat in Saigon. Deze alcoholarme pilsener heeft een knapperige smaak met een lichte zoetheid, waardoor het een perfecte keuze is om uw dorst te lessen op een warme dag in de bruisende stad.","La Bia Hoi Saigon est une bière vietnamienne populaire connue pour son caractère rafraîchissant et léger. Brassée quotidiennement, elle constitue une expérience unique dans les rues de Saigon. Cette bière blonde à faible teneur en alcool a un goût vif et légèrement sucré, ce qui en fait un choix idéal pour étancher votre soif lors d'une chaude journée dans cette ville animée.","Bia Hoi Saigon is a popular Vietnamese beer known for its refreshing and light character. Brewed daily, it's a unique street-side experience in Saigon. This low-alcohol lager has a crisp taste with a slight sweetness, making it a perfect choice for quenching your thirst on a hot day in the bustling city.",'36');

INSERT INTO `product`(`name`, `image`, `descriptionDutch`, `descriptionFrench`, `descriptionEnglish`, `price`) VALUES ('Ceylon Arrack','../../includes/indonesia.jpg',"Ceylon Arrack Indonesia is een unieke gedistilleerde drank uit Indonesië, traditioneel gemaakt van het sap van kokosbloemen. Deze alcoholische drank heeft een rijke geschiedenis en culturele betekenis in de regio. Het wordt geroemd om zijn kenmerkende smaakprofiel en is een populaire keuze voor zowel traditionele als hedendaagse cocktails.","Le Ceylon Arrack Indonesia est un spiritueux distillé unique originaire d'Indonésie, traditionnellement fabriqué à partir de la sève des fleurs de cocotier. Cette boisson alcoolisée a une histoire riche et une signification culturelle dans la région. Elle est célébrée pour son profil de saveur distinctif et constitue un choix populaire pour les cocktails traditionnels et contemporains.","Ceylon Arrack Indonesia is a unique distilled spirit originating from Indonesia, traditionally made from the sap of coconut flowers. This alcoholic beverage boasts a rich history and cultural significance in the region. It is celebrated for its distinctive flavor profile and is a popular choice for both traditional and contemporary cocktails.",'44');

INSERT INTO `product`(`name`, `image`, `descriptionDutch`, `descriptionFrench`, `descriptionEnglish`, `price`) VALUES ('Kakheti Bedoba','../../includes/mongolia.jpg',"Kakheti Bedoba is een gerenommeerde Georgische wijn uit de regio Kakheti. Deze uitzonderlijke wijn heeft een rijke geschiedenis en wordt geroemd om zijn diepe, complexe smaken. Gemaakt met behulp van traditionele wijnmaakmethoden en inheemse druivensoorten, biedt het een unieke zintuiglijke ervaring, met tonen van donker fruit, aardsheid en een vleugje specerijen.","Le Kakheti Bedoba est un vin géorgien réputé, originaire de la région de Kakheti. Ce vin exceptionnel possède une histoire riche et est réputé pour ses saveurs profondes et complexes. Élaboré selon des méthodes de vinification traditionnelles et à partir de cépages indigènes, il offre une expérience sensorielle unique, avec des notes de fruits noirs, de terre et un soupçon d'épices.","Kakheti Bedoba is a renowned Georgian wine, hailing from the Kakheti region. This exceptional wine boasts a rich history and is celebrated for its deep, complex flavors. Made using traditional winemaking methods and indigenous grape varieties, it offers a unique sensory experience, with notes of dark fruits, earthiness, and a hint of spice.",'17');

INSERT INTO `product`(`name`, `image`, `descriptionDutch`, `descriptionFrench`, `descriptionEnglish`, `price`) VALUES ('San Miguel Beer','../../includes/filipijnen.png',"San Miguel Beer is een gerenommeerd Filipijns merk dat bekend staat om zijn frisse en verfrissende lagerbieren. Het wordt al sinds 1890 gebrouwen en kan bogen op een rijk erfgoed en een zachte, evenwichtige smaak die bierliefhebbers wereldwijd aanspreekt. Het biedt een breed scala aan bierstijlen, waardoor het een populaire keuze is voor mensen die op zoek zijn naar kwaliteit en smaak.","La bière San Miguel est une marque philippine réputée pour ses lagers croustillantes et rafraîchissantes. Brassée depuis 1890, elle s'enorgueillit d'un riche héritage et d'un goût doux et équilibré qui séduit les amateurs de bière du monde entier. Elle propose un large éventail de styles de bières, ce qui en fait un choix populaire pour ceux qui recherchent la qualité et la saveur.","San Miguel Beer is a renowned Filipino brand known for its crisp and refreshing lagers. Brewed since 1890, it boasts a rich heritage and a smooth, balanced taste that appeals to beer enthusiasts worldwide. It offers a wide range of beer styles, making it a popular choice for those seeking quality and flavor.",'35');
